Handle argparse changes in Python 3.14
https://github.com/python/cpython/issues/66436 causes several tests to
fail on Python 3.14 as follows:

```
FAIL: test_global_help (test.test_command_line_interface.HelpOption.test_global_help)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.14/unittest/mock.py", line 1432, in patched
    return func(*newargs, **newkeywargs)
  File "/home/cjwatson/src/python/khard/test/test_command_line_interface.py", line 48, in test_global_help
    self._test(['-h'], r'^usage: TESTSUITE \[-h\]')
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cjwatson/src/python/khard/test/test_command_line_interface.py", line 45, in _test
    self.assertRegex(text, expect)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
AssertionError: Regex didn't match: '^usage: TESTSUITE \\[-h\\]' not found in 'usage: python -m unittest [-h] [-c CONFIG] [--debug] [--skip-unparsable] [-v] SUBCOMMAND ...\n\npositional arguments:\n  SUBCOMMAND\n    list (ls)           list all (selected) contacts\n    show (details)      display detailed information about one contact\n    template            print an empty yaml template\n    birthdays (bdays)   list birthdays (sorted by month and day)\n    email               list email addresses\n    phone               list phone numbers\n    postaddress (post, postaddr)\n                        list postal addresses\n    new (add)           create a new contact\n    add-email           Extract email address from the "From:" field of an email header and add to an existing contact or create a new one\n    merge               merge two contacts\n    edit (modify, ed)   edit the data of a contact\n    copy (cp)           copy a contact to a different addressbook\n    move (mv)           move a contact to a different addressbook\n    remove (delete, del, rm)\n                        remove a contact\n    addressbooks (abooks)\n                        list addressbooks\n    filename (file)     list filenames of all matching contacts\n\noptions:\n  -h, --help            show this help message and exit\n  -c, --config CONFIG   config file to use\n  --debug               enable debug output\n  --skip-unparsable     skip unparsable vcard files\n  -v, --version         show program\'s version number and exit\n'
```

Mock things a bit harder so that the output is as we expect.