Remove python 3.6
Python 3.6 is deprecated since December and the test run in CI is now
failing because of some undefined future feature:

SyntaxError: future feature annotations is not defined